
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:monitor-dashboard:123456@tcp(127.0.0.1:3306)/monitor-dashboard"
        jsonCase: "Snake"
        removePrefix: "xf_"

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app

  build:
    name:     "monitor-dashboard"
    arch:     "all"
    system:   "linux,darwin,windows,freebsd,openbsd,netbsd"
    mod:      "none"
    packSrc:  "resource,manifest"
    version:  "v1.0.0"
    path:     "build"
    extra:    ""