---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-single
  labels:
    app: template-single
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-single
  template:
    metadata:
      labels:
        app: template-single
    spec:
      containers:
        - name : main
          image: template-single
          resources:
            requests:
              ephemeral-storage: "2Gi"
              cpu: "100m"
              memory: "128Mi"
            limits:
              ephemeral-storage: "4Gi"
              cpu: "200m"
              memory: "256Mi"
          imagePullPolicy: Always
