// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"monitor-dashboard/internal/dao/internal"
)

// internalMachinesDao is internal type for wrapping internal DAO implements.
type internalMachinesDao = *internal.MachinesDao

// machinesDao is the data access object for table xf_machines.
// You can define custom methods on it to extend its functionality as you wish.
type machinesDao struct {
	internalMachinesDao
}

var (
	// Machines is globally public accessible object for table xf_machines operations.
	Machines = machinesDao{
		internal.NewMachinesDao(),
	}
)

// Fill with you ideas below.
